name: Prod Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: |
          az aks get-credentials \
            --resource-group sit722week10-rg \
            --name sit722week10-prod \
            --overwrite-existing

      - name: Get backend LoadBalancer IPs
        id: get-ips
        run: |
          PRODUCT_IP=$(kubectl get svc product-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          ORDER_IP=$(kubectl get svc order-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          CUSTOMER_IP=$(kubectl get svc customer-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

          echo "PRODUCT_IP=$PRODUCT_IP" >> $GITHUB_ENV
          echo "ORDER_IP=$ORDER_IP" >> $GITHUB_ENV
          echo "CUSTOMER_IP=$CUSTOMER_IP" >> $GITHUB_ENV

      - name: Inject backend IPs into frontend main.js
        run: |
          sed -i "s|const PRODUCT_API_BASE_URL = ''|const PRODUCT_API_BASE_URL = 'http://$PRODUCT_IP:5001'|" frontend/main.js
          sed -i "s|const ORDER_API_BASE_URL = ''|const ORDER_API_BASE_URL = 'http://$ORDER_IP:5002'|" frontend/main.js
          sed -i "s|const CUSTOMER_API_BASE_URL = ''|const CUSTOMER_API_BASE_URL = 'http://$CUSTOMER_IP:5003'|" frontend/main.js

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }} frontend
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}

      - name: Deploy manifests
        run: |
          kubectl set image deployment/frontend frontend=${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }} -n prod
          kubectl rollout status deployment/frontend -n prod
