name: Staging Deploy

on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_CONTAINER_REGISTRY:
        required: true
      AZURE_CONTAINER_NAME:
        required: true
      AKS_CLUSTER_STAGING:
        required: true
      RESOURCE_GROUP:
        required: true

jobs:
  staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Set Kubernetes context (get AKS credentials)
        run: |
          az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} \
                                 --name ${{ secrets.AKS_CLUSTER_STAGING }} \
                                 --overwrite-existing

      - name: Attach ACR
        run: |
          az aks update --name ${{ secrets.AKS_CLUSTER_STAGING }} \
                        --resource-group ${{ secrets.RESOURCE_GROUP }} \
                        --attach-acr ${{ secrets.AZURE_CONTAINER_NAME }}

      - name: Deploy Backend Infrastructure (DBs, ConfigMaps, Secrets)
        run: |
          cd k8s/
          kubectl apply -f configmaps.yaml
          kubectl apply -f secrets.yaml
          kubectl apply -f product-db.yaml
          kubectl apply -f order-db.yaml
          kubectl apply -f customer-db.yaml

      - name: Deploy Backend Microservices
        run: |
          cd k8s/
          kubectl apply -f product-service.yaml
          kubectl apply -f order-service.yaml
          kubectl apply -f customer-service.yaml

      - name: Deploy Frontend Service
        run: |
          cd k8s/
          kubectl apply -f frontend.yaml

      - name: Wait for all pods to be ready (up to 3 minutes)
        run: |
          for i in $(seq 1 36); do
            NOTREADY=$(kubectl get pods --no-headers | grep -v Running || true)
            if [ -z "$NOTREADY" ]; then
              echo "All pods running"
              break
            fi
            echo "Waiting for pods to be ready..."
            kubectl get pods --no-headers
            sleep 5
          done
          kubectl get pods -o wide

      - name: Get frontend external IP and run simple acceptance test
        id: acceptance
        run: |
          FRONT_SVC="frontend"
          for i in $(seq 1 60); do
            IP=$(kubectl get svc $FRONT_SVC -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "")
            if [ -n "$IP" ]; then
              echo "Frontend IP: $IP"
              break
            fi
            echo "Waiting for frontend LoadBalancer IP..."
            sleep 5
          done

          if [ -z "$IP" ]; then
            echo "ERROR: frontend LoadBalancer IP not assigned"
            kubectl get svc
            exit 1
          fi

          echo "FRONTEND_IP=$IP" >> $GITHUB_ENV
          echo "Waiting 10s for service to respond..."
          sleep 10
          echo "HTTP check:"
          curl -sSf --max-time 10 "http://$IP" || (echo "HTTP check failed"; exit 1)